# Generated by Django 5.1.3 on 2024-11-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Travel', 'Travel'), ('Education', 'Education'), ('Technology', 'Technology'), ('Artificial_Intelligence', 'Artificial Intelligence')], max_length=600),
        ),
    ]
