# Generated by Django 5.1.3 on 2024-12-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_comment_time_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Travel', 'Travel'), ('Education', 'Education'), ('Technology', 'Technology'), ('ArtificialIntelligence', 'ArtificialIntelligence')], max_length=600),
        ),
    ]
