# Generated by Django 5.1.3 on 2024-12-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Travel', 'Travel'), ('Education', 'Education'), ('Technology', 'Technology'), ('AI', 'AI')], max_length=600),
        ),
    ]
